# ESTADOS
estados =[ 
    'q0', 'id', 
    'i', 'in', 'int', 'if',
    'int_parenteses_esq', 'int_parenteses_dir', 'int_espaco',
    'if_parenteses_esq', 'if_espaco',
    'f', 'fl', 'flo', 'floa', 'float',
    'float_parenteses_esq', 'float_parenteses_dir', 'float_espaco',
    'e', 'el', 'els', 'else',
    'w', 'wh', 'whi', 'whil', 'while', 
    'while_parenteses_esq', 'while_espaco',
    'r', 're', 'ret', 'retu', 'retur', 'return'
    'return_parenteses_esq', 'return_ponto_virgula', 'return_espaco',
    'v', 'vo', 'voi', 'void',
    'else_chaves_esq', 'else_espaco',
    'number', 'number_parenteses_esq', 'number_parenteses_dir', 'number_colchetes_esq', 'number_colchetes_dir', 'number_chaves_esq', 'number_chaves_dirs',
    'number_ponto_virgula', 'number_virgula', 'number_espaco',
    'number_adicao', 'number_subtracao', 'number_multiplicacao', 'number_divisao', 'number_maior', 'number_menor', 'number_atribuicao', 'number_exclamacao', 
    'adicao', 'subtracao', 'multiplicacao', 'divisao',
    'maior', 'maior_igual', 'menor', 'menor_igual',
    'parenteses_esq', 'parenteses_dir',
    'colchetes_esq', 'colchetes_dir',
    'chaves_esq', 'chaves_dirs',
    'virgula', 'ponto_virgula', 'ponto',
    'atribuicao', 'igual','atribuicao_finalizado',
    'exclamacao', 'exclamacao_igual',
    'void_parenteses_dir', 'void_ponto_virgula', 'void_espaco',
    'divisao_finalizado', 'divisao_equal', 'divisao_id', 'divisao_number',
    'maior_finalizado', 'menor_finalizado',
    'id_parenteses_esq', 'id_parenteses_dir', 'id_colchetes_esq', 'id_colchetes_dir', 'id_chaves_esq', 'id_chaves_dirs',
    'id_ponto_virgula', 'id_virgula', 'id_espaco',
    'id_adicao', 'id_subtracao', 'id_multiplicacao', 'id_divisao', 'id_maior', 'id_menor', 'id_atribuicao', 'id_exclamacao',
    'divisao_multiplicacao', 'comentario', 'comentario_multiplicacao', 'comentario_finalizado',
]