# ALFABETO DE SAIDA
alfabetoSaidas =[ 
    'INT',
    'FLOAT',
    'IF',
    'ELSE',
    'NUMBER'
    'RETURN',
    'VOID',
    'WHILE',
    'COMMA',
    'SEMICOLON',
    'LPAREN',
    'RPAREN'
    'LBRACKETS',
    'RBRACKETS',
    'LBRACES',
    'RBRACES',
    'GREATER',
    'GREATER_EQUAL',
    'LESS',
    'LESS_EQUAL',
    'PLUS',
    'MINUS',
    'TIMES',
    'DIVIDE',
    'ATTRIBUTION',
    'DIFFERENT',
    'EQUALS',
    'ID',
]

# TABELA DE SAÍDA
tabelaSaidas = { 
    'q0' : '',
    'numero' : '',
    'numero_parenteses_esq' : 'NUMBER\nLPAREN\n',
    'numero_parenteses_dir' : 'NUMBER\nRPAREN\n',
    'numero_colchetes_esq' : 'NUMBER\nLBRACKETS\n',
    'numero_colchetes_dir' : 'NUMBER\nRBRACKETS\n',
    'numero_chaves_esq' : 'NUMBER\nLBRACES\n',
    'numero_chaves_dirs' : 'NUMBER\nRBRACES\n',
    'numero_virgula' : 'NUMBER\nCOMMA\n',
    'numero_ponto_virgula' : 'NUMBER\nSEMICOLON\n',
    'numero_adicao' : 'NUMBER\nPLUS\n',
    'numero_subtracao' : 'NUMBER\nMINUS\n',
    'numero_multiplicacao' : 'NUMBER\nTIMES\n',
    'numero_divisao' : 'NUMBER\nDIVIDE\n',
    'numero_menor' : 'NUMBER\nLESS\n',
    'numero_maior' : 'NUMBER\nGREATER\n',
    'numero_atribuicao' : 'NUMBER\nATTRIBUTION',
    'numero_exclamacao' : 'NUMBER\nDIFFERENT\n',
    'numero_espaco' : 'NUMBER\n',
    'i' : '',
    'if' : '',
    'if_parenteses_esq' : 'IF\nLPAREN\n',
    'if_espaco' : 'IF\n',
    'in' : '',
    'int' : '',
    'int_parenteses_esq' : 'INT\nLPAREN\n',
    'int_parenteses_dir' : 'INT\nRPAREN\n',
    'int_espaco' : 'INT\n',
    'f' : '',
    'fl' : '',
    'flo' : '',
    'floa' : '',
    'float' : '',
    'float_parenteses_esq' : 'FLOAT\nLPAREN\n',
    'float_parenteses_dir' : 'FLOAT\nRPAREN\n',
    'float_espaco' : 'FLOAT\n',
    'e' : '',
    'el' : '',
    'els' : '',
    'else' : '',
    'else_chaves_esq' : 'ELSE\nLBRACES\n',
    'else_espaco' : 'ELSE\n',
    'r' : '',
    're' : '',
    'ret' : '',
    'retu' : '',
    'retur' : '',
    'return' : '',
    'return_parenteses_esq' : 'RETURN\nLPAREN\n',
    'return_ponto_virgula' : 'RETURN\nSEMICOLON\n',
    'return_espaco' : 'RETURN\n',
    'v' : '',
    'vo' : '',
    'voi' : '',
    'void' : '',
    'void_parenteses_dir' : 'VOID\nRPAREN\n',
    'void_ponto_virgula' : 'VOID\nSEMICOLON\n',
    'void_espaco' : 'VOID\n',
    'w' : '',
    'wh' : '',
    'whi' : '',
    'whil' : '',
    'while' : '',
    'while_parenteses_esq' : 'WHILE\nLPAREN\n',
    'while_espaco' : 'WHILE\n',
    'parenteses_esq' : 'LPAREN\n',
    'parenteses_dir' : 'RPAREN\n',
    'colchetes_esq' : 'LBRACKETS\n',
    'colchetes_dir' : 'RBRACKETS\n',
    'chaves_esq' : 'LBRACES\n',
    'chaves_dirs' : 'RBRACES\n',
    'adicao' : 'PLUS\n',
    'subtracao' : 'MINUS\n',
    'multiplicacao' : 'TIMES\n',
    'divisao' : '',
    'divisao_multiplicacao' : '',
    'comentario' : '',
    'comentario_multiplicacao' : '',
    'comentario_fim' : '',
    'maior' : '',
    'maior_igual' : 'GREATER_EQUAL\n',
    'maior_fim' : 'GREATER\n',
    'menor' : '',
    'menor_igual' : 'LESS_EQUAL\n',
    'menor_fim' : 'LESS\n',
    'atribuicao' : '',
    'igual' : 'EQUALS\n',
    'atribuicao_fim' : 'ATTRIBUTION\n',
    'exclamacao' : '',
    'exclamacao_igual' : 'DIFFERENT\n',
    'id' : '',
    'id_parenteses_esq' : 'ID\nLPAREN\n',
    'id_parenteses_dir' : 'ID\nRPAREN\n',
    'id_colchetes_esq' : 'ID\nLBRACKETS\n',
    'id_colchetes_dir' : 'ID\nRB RACKETS\n',
    'id_chaves_esq' : 'ID\nLBRACES\n',
    'id_chaves_dirs' : 'ID\nRBRACES\n',
    'id_virgula' : 'ID\nCOMMA\n',
    'id_ponto_virgula' : 'ID\nSEMICOLON\n',
    'id_adicao' : 'ID\nPLUS\n',
    'id_subtracao' : 'ID\nMINUS\n',
    'id_multiplicacao' : 'ID\nTIMES\n',
    'id_divisao' : 'ID\nDIVIDE\n',
    'id_maior' : 'ID\nGREATER\n', 
    'id_menor' : 'ID\nLESS\n', 
    'id_atribuicao' : 'ID\nATTRIBUTION\n', 
    'id_exclamacao' : 'ID\nDIFFERENT\n', 
    'id_espaco' : 'ID\n',
    'ponto' : '',
    'virgula' : 'COMMA\n',
    'ponto_virgula' : 'SEMICOLON\n',
}